# Generated by Django 2.2.6 on 2019-12-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('role', models.CharField(choices=[('1', 'Judge 1'), ('2', 'Judge 2'), ('3', 'Judge 3')], max_length=1)),
            ],
        ),
    ]
