# Generated by Django 3.0 on 2019-12-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'judge1'), (4, 'judge2'), (5, 'judge3'), (6, 'admin')], null=True),
        ),
    ]
