# Generated by Django 3.0 on 2020-01-25 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('province', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=100, null=True)),
                ('learnergrade', models.CharField(blank=True, max_length=100, null=True)),
                ('parentname', models.CharField(blank=True, max_length=200)),
                ('parentphone', models.CharField(blank=True, max_length=100, null=True)),
                ('parentemail', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('teachername', models.CharField(blank=True, max_length=300)),
                ('teacherphone', models.CharField(max_length=100, null=True)),
                ('teacheremail', models.CharField(max_length=100, null=True)),
                ('worktitle', models.CharField(max_length=300, null=True)),
                ('workfile', models.FileField(upload_to='works')),
                ('workfileCropped', models.TextField(default='')),
                ('workformulafile', models.FileField(blank='True', null=True, upload_to='formulas')),
                ('workapproved', models.BooleanField(default=False)),
                ('bioapproved', models.BooleanField(default=False)),
                ('qapproved', models.BooleanField(default=False)),
                ('question1', models.TextField()),
                ('question2', models.TextField()),
                ('question3', models.TextField()),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(-1, 'Partially Submitted'), (0, 'Submitted Successfully'), (1, 'Revision Required'), (2, 'Rejected Stage 0'), (3, 'Accepted Stage 0'), (4, 'Waiting For Decision'), (5, 'Accepted Stage 1'), (6, 'Rejected Stage 1'), (7, 'Waiting For Artpost'), (8, 'Rejected Stage 2'), (9, 'Artpost Recieved'), (10, 'Rejected Stage 3'), (11, 'Winner')], default=-1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted'],
            },
        ),
    ]
