# Generated by Django 3.0 on 2020-02-14 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnergrade', models.CharField(blank=True, max_length=100, null=True)),
                ('teachername', models.CharField(blank=True, max_length=300)),
                ('teacherphone', models.CharField(blank=True, max_length=100, null=True)),
                ('teacheremail', models.CharField(blank=True, max_length=100, null=True)),
                ('worktitle', models.CharField(blank=True, max_length=300, null=True)),
                ('workfile', models.FileField(blank=True, null=True, upload_to='works')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='works')),
                ('workfileCropped', models.TextField(blank=True, default='', null=True)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('workformulafile', models.FileField(blank='True', null=True, upload_to='formulas')),
                ('workapproved', models.BooleanField(default=False)),
                ('bioapproved', models.BooleanField(default=False)),
                ('qapproved', models.BooleanField(default=False)),
                ('question1', models.TextField(blank=True, max_length=100)),
                ('question2', models.TextField(blank=True)),
                ('question3', models.TextField(blank=True)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(-1, 'Pending'), (0, 'Submitted'), (1, 'Requires Revision'), (2, 'Revised work'), (3, 'Rejected Stage 0'), (4, 'Accepted Stage 0'), (5, 'Waiting For Decision'), (6, 'Accepted Stage 1'), (7, 'Rejected Stage 1'), (8, 'Waiting For Artpost'), (9, 'Rejected Stage 2'), (10, 'Artpost Recieved'), (11, 'Rejected Stage 3'), (12, 'Winner')], default=-1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.School')),
            ],
            options={
                'ordering': ['submitted'],
            },
        ),
    ]
