# Generated by Django 2.2.6 on 2019-12-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='dateofbirth',
        ),
        migrations.AddField(
            model_name='artwork',
            name='age',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
