# Generated by Django 2.2.6 on 2019-12-16 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0001_initial'),
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='evald1a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluation.EvalD1A'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='evald1b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluation.EvalD1B'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='evald1c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluation.EvalD1C'),
        ),
    ]
