# Generated by Django 3.0 on 2020-02-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
