# Generated by Django 3.0 on 2020-01-31 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='bioapproved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='qapproved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='question1',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='question2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='question3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='teacheremail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='teacherphone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='workapproved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='workfileCropped',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='worktitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
