# Generated by Django 3.0 on 2020-01-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20200131_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='province',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
