# Generated by Django 3.0 on 2020-01-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20191230_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='artwork',
            name='workfileCropped',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='province',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='firstname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='question1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='question2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='question3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='school',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='surname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='teacheremail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='workfile',
            field=models.FileField(upload_to='works'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='worktitle',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterIndexTogether(
            name='artwork',
            index_together=set(),
        ),
    ]
