# Generated by Django 2.2.6 on 2019-12-16 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0001_initial'),
        ('artwork', '0002_auto_20191216_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='evald1b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluation.EvalD1B'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='evald1c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluation.EvalD1C'),
        ),
    ]
