# Generated by Django 2.2.6 on 2019-12-02 18:35

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20191202_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='learnergrade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='parentemail',
            field=models.EmailField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='parentname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='parentphone',
            field=phone_field.models.PhoneField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='question1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='question2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='question3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='teacheremail',
            field=models.EmailField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='teachername',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='teacherphone',
            field=phone_field.models.PhoneField(blank=True, max_length=18),
        ),
    ]
