# Generated by Django 3.0 on 2020-01-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_auto_20200104_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='workformulafile',
            field=models.FileField(blank='True', null=True, upload_to='formula'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='parentemail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='teacherphone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
