# Generated by Django 2.2.6 on 2019-12-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_auto_20191216_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='evald1a',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluation.EvalD1A'),
        ),
    ]
