# Generated by Django 2.2.6 on 2019-12-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_auto_20191202_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='learnergrade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
