# Generated by Django 2.2.6 on 2019-12-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_auto_20191202_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='testomonial',
            new_name='testimonial',
        ),
    ]
