# Generated by Django 3.0 on 2020-01-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_auto_20200131_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='bioapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='qapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='workapproved',
            field=models.BooleanField(default=False),
        ),
    ]
