# Generated by Django 3.0 on 2020-01-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_auto_20200109_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='d1a',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='d1b',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='d2',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='d3',
        ),
    ]
