# Generated by Django 3.0 on 2020-02-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_auto_20200131_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='works'),
        ),
    ]
