# Generated by Django 2.2.6 on 2019-12-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_auto_20191202_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['surname']},
        ),
    ]
