# Generated by Django 3.0 on 2020-02-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_artwork_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
