# Generated by Django 3.0 on 2020-01-25 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0006_auto_20200112_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='email',
        ),
        migrations.AddField(
            model_name='artwork',
            name='user',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Partially Submitted'), (0, 'Submitted Successfully'), (1, 'Revision Required'), (2, 'Rejected Stage 0'), (3, 'Accepted Stage 0'), (4, 'Waiting For Decision'), (5, 'Accepted Stage 1'), (6, 'Rejected Stage 1'), (7, 'Waiting For Artpost'), (8, 'Rejected Stage 2'), (9, 'Artpost Recieved'), (10, 'Rejected Stage 3'), (11, 'Winner')], default=-1),
        ),
    ]
