# Generated by Django 3.0 on 2020-01-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0007_auto_20200125_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='user',
        ),
        migrations.AddField(
            model_name='artwork',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
